### ISSUE TITLE
(Feature request) Adding a resolution display

### ISSUE THREAD

**Issue by Osha31** [masagrator/Status-Monitor-Overlay#10]
I'm not sure how feasible this is, but could it be possible to have some sort of counter or something that shows off what resolution a game is currently running in ? I think it would be nice for games that have a dynamic resolution.

**Comment by masagrator** [comment]
It's not possible to make universal method. We have three resolutions to discuss: output resolution, window resolution and rendering resolution.

Output is available only for system - 480p, 720p, 1080p. Nothing else.
Window resolution is available for games by using system function. Games are using only two resolutions here: 720p and 1080p.
Rendering is available for game only and there is no standard to use it. Each engine implements it differently, so you would need to make game by game basis, which is time consuming. This what most people want to get.

So no - it's not possible.
