### ISSUE TITLE
(Feature request) battery voltage

### ISSUE THREAD

**Issue by chrisf95** [masagrator/Status-Monitor-Overlay#12]
Hi, is possible to display the voltage of the battery in the overlay (full and mini)? Because my switch have a strange issue, a battery de-sync, that reset to 0% at every long shutdown and the only way to know the percentage (approximately obv) is the voltage (that for now I can see only in helate)
I hope is possible and thanks any way 😊

**Comment by masagrator** [comment]
Well, it's possible, but I didn't want to include it as mandatory.
I can add custom version here. I'm trying to figure out how to implement drawing readings so each category will be optional. Then I will add it as optional.

**Comment by chrisf95** [comment]
Yeah, It Will be fantastic... For now I play with the fear of the battery alert 😂

**Comment by masagrator** [comment]
Sorry, but it seems it may not be possible atm. I don't see any function that can get battery voltage in libnx

**Comment by chrisf95** [comment]
Thanks anyways

**Comment by masagrator** [comment]
Ok, digged deeper and I have found where "voltage now" is stored. It will require to add custom code. I will still do tests with separate overlay to figure out what some unknown fields means.

**Comment by masagrator** [comment]
![2020101021404700-57B4628D2267231D57E0FC1078C0596D](https://user-images.githubusercontent.com/8557858/95663593-cff9d000-0b40-11eb-92e9-ef12d92cad70.jpg)

**Comment by chrisf95** [comment]
Really really Happy 😍 I hope we can use It soon 😊

**Comment by chrisf95** [comment]
Ho, I see the GitHub Page of the test you did, how can I compile It?

**Comment by masagrator** [comment]
Like usual. devkitpro, switch-dev and make. There is nothing additional

**Comment by chrisf95** [comment]
> Like usual. devkitpro, switch-dev and make. There is nothing additional

Thanks

**Comment by chrisf95** [comment]
I managed to compile It after some difficulty... I hope to see the possible integration in main overlay (for example for some value like voltage) in order to see it in mini interfaces. However really thanks, so I can see the voltage (and in this way the charge of my battery) without injecting hekate

**Comment by masagrator** [comment]
Added opt-in mode that shows battery stats instead of RAM in Full Mode. I have decided to not include it in mini mode.

**Comment by chrisf95** [comment]
> Added opt-in Full mode called `Custom` that shows battery stats instead of RAM. You need to define `CUSTOM` either in main.cpp or in makefile. I have decided to not include it in mini mode.

Thanks, I Will try in this day.

**Comment by muxi1** [comment]
I would also be very interested in this new feature with the battery voltage display. However, when compiling with the current libnx 4.1.3 I get numerous error messages related to the control elements. Can someone please attach a working compiled version here? Thanks in advance.

**Comment by kelke** [comment]
I would also love seeing battery info in the default overlay :)
