### ISSUE TITLE
(Feature request) Show my ip on the network

### ISSUE THREAD

**Issue by victorgneves** [masagrator/Status-Monitor-Overlay#14]
I would like to be able to see in one place the switch IP on the network, to connect the FTP.
It may be Full mode.
Just like Edizon> System Information> Local IP.
Just an idea.

Another useful thing would be the battery percentage of the Pro Controler.

Congratulations for the project.

**Comment by masagrator** [comment]
I don't plan to add any of them to status monitor.

IP can be checked with sys-ftpd-ovl.
