### ISSUE TITLE
documentation on temporary overrides

### ISSUE THREAD

**Issue by eodrambo** [masagrator/Status-Monitor-Overlay#16]
I was looking over your readme. There's no mention of how long the temporary overrides stay in place. Weather it's until a new game or app is launched, another profile is loaded, when the system is restarted, 30 minutes, or maybe they're just system wide permanent overrides. 

Could you add some clarity to your documentation?
I love your work, and if I've missed where it is already documentated, I apologize. Thanks again!

**Comment by masagrator** [comment]
What temporary overrides? I don't have anything like that in Status Monitor.

You didn't mistake it for sys-clk overlay which has option for clocks temporary override?

**Comment by eodrambo** [comment]
God, Im a total idiot!! Sorry. Please remove this
