### ISSUE TITLE
Overlay froze up

### ISSUE THREAD

**Issue by lajax01** [masagrator/Status-Monitor-Overlay#2]
Hi.
I can activate the overlay, but after that, I cannot reach Tesla overlay menu.
(L+Down+R stick click wont work after activated statusmonitor.)
So, I cannot use another, or deactivate current.
Pls see after this issue.
Latest fw 9.2, with latest Atmosphere, and Tesla.
(Fresh install after update.)
Thx in advance, and respect for your work!

**Comment by lajax01** [comment]
Never mind.. Im accidentaly solve.. If you already use this, push the two analog stick together. :/
Poor readme it is..

**Comment by masagrator** [comment]
```
You can exit from selected mode by pressing and holding Left Stick + Right Stick. To exit from main menu press B.
```
"Poor readme"... Maybe you are a poor reader?
And default combo is not working because of bug I introduced somewhere to fork.

**Comment by lajax01** [comment]
Could by... Im does not found this info under this repo. 
If exist, please forgive me.
