### ISSUE TITLE
hard crash on opening battery tab

### ISSUE THREAD

**Issue by davidv2002** [masagrator/Status-Monitor-Overlay#27]
[01668306952_420000000007e51a.log](https://github.com/masagrator/Status-Monitor-Overlay/files/9996390/01668306952_420000000007e51a.log)
[01668306952_420000000007e51a_thread_info.txt](https://github.com/masagrator/Status-Monitor-Overlay/files/9996392/01668306952_420000000007e51a_thread_info.txt)
![IMG_20221112_193822_699](https://user-images.githubusercontent.com/31711326/201503062-30a33f8b-2678-4b15-bb93-e5d8c697ed69.jpg)
attached are all files related to the crash, the bin file is renamed to a txt as it would not upload.
here is what happened, I have a rev 1 switch version of horizon and atmosphere are shown in the picture. I just updated this olv and had no others running, I opened up youtube to check out the NVDEC clock thing as a google search said it was a video decoder, after checking that while playing back a video I opened the battery tab, the switch was plugged into a usb 3.0 port on my laptop. the console instantly crashed to the screen shown in the image and was unable to restart and had to be fully powered off.

**Comment by masagrator** [comment]
Issue is I can't repeat this.
Crash reports show nothing valuable in this case.

Does this happen every time you will repeat those steps?

**Comment by davidv2002** [comment]
just checked and I guess it was a random crash, should have tried again at the time but hard crashes are not fun. sorry for wasting your time
