### ISSUE TITLE
Battery Tab + Mini and Full tab freezing

### ISSUE THREAD

**Issue by Horrent** [masagrator/Status-Monitor-Overlay#28]
![20221217_010835](https://user-images.githubusercontent.com/116696849/208228225-4ededf23-d84e-4f1d-88f7-12cbc410c6a6.jpg)
![20221217_010747](https://user-images.githubusercontent.com/116696849/208228228-517f7309-0200-4ca7-8cc7-7dda04ad3d39.jpg)
![20221217_010857](https://user-images.githubusercontent.com/116696849/208228233-fa4a7104-8c6c-4dd5-9dda-69bcdca24f0c.jpg)
![20221217_010903](https://user-images.githubusercontent.com/116696849/208228237-47a63aee-da02-4590-aabe-6a2e8ac4e3b0.jpg)

This happens on a 15.0.1 Oled Switch with latest atmosphere and hekate files. It can be recreated by just clicking on the tabs and sometimes you'll see it working and when it doesn't work it would show null values and that's when it hangs. the only way to unfreeze it is to press the sleep button and when it wakes up from sleep I see the tesla overlay menu which I'm able to remove the opened tab.

**Comment by masagrator** [comment]
Your CPU Core 3 has 100% usage. This is a sign you are using some butchered custom sysmodule without proper thread sleeping implemented, or you are using nifm patches and you are connected to local network without connected internet which causes the same issues

**Comment by Horrent** [comment]
I don't know what nifm patches are but this could also explain the battery drain during sleep that happens randomly. I've even got as far as clearing the sd card and just installing system monitoring and tesla + tesla ovloader. Current modules are sysdvr, mission control and salty nx. And overlays are sysdvr, sys-clk , sys modules , and sys monitor.

**Comment by Horrent** [comment]
closing this issue as its not a issue on your end. fixed it by completely scraping the sd card and following the written guide for mariko and it seem to solve my issue. shows that these "complete package" files from guides are faulty. thanks for the reply. wouldnt have figured out it was my atmosphere and hekate files causing this

**Comment by orbitinstasis** [comment]
> Your CPU Core 3 has 100% usage. This is probably a sign you are using some butchered custom sysmodule without proper thread sleeping implemented, or you are using nifm patches and you are connected to local network without connected internet which causes the same issues

Could you elaborate on this ? I'm on 15.0.1, and my monitor show's things correctly, for example loading zelda, i can see the GPU and CPU clock changing in the menu --> loading --> game, but around the game, it jumps to 99.x% then the overlay completely crashes. I've gone and removed all of the otehr sysmodules, and am not really sure what a nifm patch is. Do you have any idea why this might be happening?

**Comment by orbitinstasis** [comment]
> Your CPU Core 3 has 100% usage. This is probably a sign you are using some butchered custom sysmodule without proper thread sleeping implemented, or you are using nifm patches and you are connected to local network without connected internet which causes the same issues

Sorry for the double post. You mentioned something about nifm patches+ local network + no internet. I am using a file in 'hosts' to block certain servers, but can definitely connect to the internet, and am obviously on a local network - however I don't know what nifm patches are - alas I stuck my switch in flight mode, and the overlay just jumped back to life, and it works fully as expected without the 100% third core. 

Could you maybe point me in the right direction as to fix any potential issue I have, or what 'nifm patches' are? I tried googling but I can't find anything too helpful.

Thanks a lot.

**Comment by masagrator** [comment]
they are also called ctest patches.

You should have in atmosphere/exefs_patches folder with "nifm" and/or "ctest" in name. If it's there, delete it and restart Switch.

**Comment by orbitinstasis** [comment]
> they are also called ctest patches.
> 
> You should have in atmosphere/exefs_patches folder with `nifm` (or `nfim` as I see in original repo it's mispelled) and/or `ctest` in name. If it's there, delete it and restart Switch.

Thanks for the reply, i see the exefs patches nfim_ctest folder from sigpatches - i imagine a work around is using flight mode for monitoring.

**Comment by masagrator** [comment]
dunno why sigpatches started to use it, but only use of this is to connect to network that has no internet connection (since in normal case Switch would cancel connecting to such network). If you don't have such a speficic use case, just delete folder.

**Comment by orbitinstasis** [comment]
'nfim_ctest' is a patch that lets you connect to a network when there's no internet connection? Do you mean a local network? Also, would you mind telling me what kind of use cases nfim_ctest are for?

**Comment by masagrator** [comment]
Local network is always available on Wi-Fi. I mean that normally you can't connect with Nintendo Switch to Wi-Fi if it doesn't have internet connection.
With those patches you can do that.

For example you want to stream PC to your Switch via Wi-Fi that has no internet connection. You put this patch and bam - it works.

**Comment by orbitinstasis** [comment]
Oh, literally connecting to an access point without internet. Why would you want to do that? to do local stuff? I assume most things are connected to the internet now. I'm trying to think of a use case that might apply to me. I could rename the folder to something else for now so they're not used, and rename back if required later, do you think that would be a safe way to 'remove' the folder while i test?

**Comment by masagrator** [comment]
Renaming folder won't change anything. You must move it or delete it from exefs patches.

**Comment by Horrent** [comment]
So I just wanted to add that clearing my sd card did not help. SOLUTION: it turned out to be that since my sysnand had a nintendo account linked and since my device was not the primary switch when I had created a emmunand all that was copied over and when ever I ran a game I was on a constant check loop hence the 3rd core always on 99% and would only stop if I turned on airplane mode. There's 2 solutions and one isn't tested but seems like it would work. 1st one was to start over.... go to sysnand and format everything and unlink the account then create a emmunand all over (worked for me).
2. Would be to use linkalho to remove the linked switch account that was causing the issue. (Not tested by me but worked for a friend who had the same issue)

**Comment by orbitinstasis** [comment]
> Renaming folder won't change anything. You must move it or delete it from exefs_patches.

I did as you said by removing the nfim_ctest from exefs_patches and the errors remains until i turn on flight mode. status monitor continues showing correct core %s I assume with 100% at core 3, and as soon as i turn on flight mode core 3 jumps back to a sane load and the rest of the monitors update regularly.

**Comment by masagrator** [comment]
Do what user above you posted if you are in similar situation.

**Comment by orbitinstasis** [comment]
seems to work well outside of BOTW - don't think the above user has the problem i have since in another game 3rd core is not maxing out. anyway thanks both for your help.

**Comment by orbitinstasis** [comment]
> So I just wanted to add that clearing my sd card did not help. SOLUTION: it turned out to be that since my sysnand had a nintendo account linked and since my device was not the primary switch when I had created a emmunand all that was copied over and when ever I ran a game I was on a constant check loop hence the 3rd core always on 99% and would only stop if I turned on airplane mode. There's 2 solutions and one isn't tested but seems like it would work. 1st one was to start over.... go to sysnand and format everything and unlink the account then create a emmunand all over (worked for me). 2. Would be to use linkalho to remove the linked switch account that was causing the issue. (Not tested by me but worked for a friend who had the same issue)

I tried a combination of unlinking and linking in linkalho, after unlinking in linkalho i would get sign in prompts for each program, so i tried relinking (I tried this a few times) and it seems to have done the trick. 

Did your friend relink in linkalho?
