### ISSUE TITLE
Switch freezes on opening Album

### ISSUE THREAD

**Issue by dnsBlah** [masagrator/Status-Monitor-Overlay#29]
While having NX-FPS setup and opening the Album whilst there is a game running, the switches freezes up badly.

No atmosphere crash or anything.
Only way to power off to force power.

If 'fast' enough, you can select power options > shutdown but will result in endless spinning icon.

Is there anything that can be done to prevent this?

HOS 15.0.1
Chainloading Atmosphere 1.4.0 using Hekate v5.9.0

**Comment by Lamcza** [comment]
> While having NX-FPS setup and opening the Album whilst there is a game running, the switches freezes up badly.
> 
> No atmosphere crash or anything. Only way to power off to force power.
> 
> If 'fast' enough, you can select power options > shutdown but will result in endless spinning icon.
> 
> Is there anything that can be done to prevent this?
> 
> HOS 15.0.1 Chainloading Atmosphere 1.4.0 using Hekate v5.9.0

i mean it is still here but idk meaybe it is just to demanding to handle all of this at once :X?

**Comment by masagrator** [comment]
It's not demanding. This is a rare issue because it never happened to me or anybody else that I know. And without a sure way to reproduce issue I can't help

**Comment by Lamcza** [comment]
Was able to crush it 4 times before figuring out that it was crushing when the status monitor was up. But it created an error log on the first crush only somehow. Not rlly sure if it is fps fault but it is crushing exactly like the op wrote. 
I sent you that log on gba.

**Comment by masagrator** [comment]
Lamcza issue was solved by deleting ftpd light.

**Comment by Lamcza** [comment]
Yep just turning it off works for me. Album is flying alongside with game in the background and a status monitor on the screen.

**Comment by masagrator** [comment]
@dnsBlah issue still persists?
