### ISSUE TITLE
HB App Store release does not install overlay

### ISSUE THREAD

**Issue by v1993** [masagrator/Status-Monitor-Overlay#35]
After updating from an older version I've discovered that Status Monitor Overlay disappeared from tesla menu. Checking `switch/.overlays` revealed that file simply is not there. Reinstalled a few times to no avail.

Downloading and installing manually from from GitHub Releases works just fine.

**Comment by TTghostsemir** [comment]
If you download it from Hbappstore the overlay is in Sd/.overlays copy the overlay to Sd/switch/.overlays

**Comment by masagrator** [comment]
It's fixed.
