### ISSUE TITLE
Status Monitor Freezing Games

### ISSUE THREAD

**Issue by GrimMeNaCe** [masagrator/Status-Monitor-Overlay#44]
Shredders Revenge, San Andreas etc. freeze when clicking on Status Monitor. Status Monitor doesn't show up after clicking on it and after a bit when you try playing the game, it will lock up. Sometimes things will work if I use Status Monitor before clicking on the game.

Latest Atmosphere, latest Switch firmware, latest Tesla overlay.

**Comment by masagrator** [comment]
Remove some sysmodules and try again. Status Monitor requires more memory than typical overlay, so if your custom sysmodules take too much RAM memory it can freeze or crash system.

**Comment by GrimMeNaCe** [comment]
Thank you, that solved the problem, and thank you for making me aware of the read me for SaltyNX, appreciate the help and guidance.
