### ISSUE TITLE
Can't exit status monitor but other overlays work fine

### ISSUE THREAD

**Issue by mtoensing** [masagrator/Status-Monitor-Overlay#45]
I followed the steps for the installation. Works fine. I can choose between 6 different modes. But when I try to use another overlay like chk sw nothing happens. I can alter the position of the FPS overlay with RZ,R + up/down. Nothing else works. I have to reboot to payload to get rid of the overlay. Any idea?

**Comment by masagrator** [comment]
Read readme.
