### ISSUE TITLE
FPS Counter stops working when connected to a wi-fi network

### ISSUE THREAD

**Issue by theimpatientsamurai** [masagrator/Status-Monitor-Overlay#46]
This one's an odd one, the fps counter works perfectly fine with all menus, but as soon as I connect to the internet, it just freezes the counter at 254, and the menu itself wont pop-up either when clicking the two thumbsticks down, nor will the tesla menu if I click the shortcut to get into Tesla. the only way to fix it is to be in airplane mode, or to click the thumbsticks, put the console to sleep, and turn it back on, which it then pops up the menu upon starting back up. 
It's an odd problem, but I can provide screenshots or a video if you want to see it happening. I can also provide more info if needed as well, but I tried it with nothing else installed homebrew-wise, and it still has this problem.

**Comment by masagrator** [comment]
Read troubleshooting section since it sounds like it's related. You can't just even go to any mode to find out your core is at 100%

**Comment by theimpatientsamurai** [comment]
That was the issue! Thanks for letting me know, I'll have to keep it on airplane mode from now on then
