### ISSUE TITLE
Overlay causes softlock

### ISSUE THREAD

**Issue by roxzii** [masagrator/Status-Monitor-Overlay#47]
When used in game as soon as I open tesla menu and select status monitor overlay tesla menu disappears and the switch softlocks until I do a hard reboot. Horizon power option how up but do not turn the switch off. Happens on all games. I am running atmosphere 1.5.4 pre release + hekate 6.0.4 + horizon 16.0.3. All other overlay's work perfectly. Only happened after I did a full update of SaltyNX+FPSLocker+NX-FPS+Status Monitor Overaly.

EDIT: If i start the overlay on the home menu it works, and continues to work when I enter a game, but as soon as I press the sticks to go back to the overlay it softlocks again. If I go back to the overlay in the home menu it works normally. So it only happens in game.

**Comment by masagrator** [comment]
Remove all other sysmodules and try again.
If it still happens, check what CPU Core 3 Usage shows when game is running.

**Comment by roxzii** [comment]
Thank you! Found the sysmodule that was causing trouble. In case anyone has this problem it was caused by "sys-screenuploader".

**Comment by masagrator** [comment]
Yeah, it is known for taking huge chunk of sysmodule space in comparison to other sysmodules. It takes few times more RAM than SaltyNX.
