### ISSUE TITLE
FPS Counter stuck at 255

### ISSUE THREAD

**Issue by LaunchpadPhil** [masagrator/Status-Monitor-Overlay#6]
the title says it all (Im on Atmosphere if that helps)

**Comment by masagrator** [comment]
> the title says it all

But it doesn't.

**Comment by LaunchpadPhil** [comment]
okay reformulating I was tired and didnt know what to write exactly.
So The FPS counter is stuck at 255 with the switch firmware 10.0.1 and latest atmosphere version I tried it with Astral Chain, BOTW, the homescreen and Mario Maker still stuck at 255.

**Comment by masagrator** [comment]
- List of all used sysmodules with versions
- is SaltyNX you are using the newest one
- Is SaltyNX-Tool showing that SaltyNX is properly injected

**Comment by LaunchpadPhil** [comment]
Okay I solved I was a complete reatrd and didnt download saltynx
