### ISSUE TITLE
Question about the battery module

### ISSUE THREAD

**Issue by mangoppola** [masagrator/Status-Monitor-Overlay#61]
I have my switch connected to the official charger. The voltage is $15\mathrm V$, and the current flow is around $+2000\mathrm{mA}$. The battery power flow is reported to be $\approx 8.5\mathrm W$, but I would expect that to be closer to $15\mathrm V \times 2\mathrm A = 30\mathrm W$.  
Is the reported value wrong or am I missing something?

**Comment by masagrator** [comment]
Hardware blocks charging at max 2A. Battery voltage increases up to 4.3V when charged. So max charging possible is 8.6W. 

Surplus of what charger provides is provided to hardware, bypassing battery.

It's possible to force hardware to accept max 3A, but it's unsafe and thus no homebrew provides an option to unblock it.
