### ISSUE TITLE
Latest version doesn't close overlay on L3+R3 anymore. (HOS17)

### ISSUE THREAD

**Issue by QuinTeknoLife** [masagrator/Status-Monitor-Overlay#69]
I just updated the overlay to 1.0.1 and now I can't close the overlay anymore, on ~~the previous version~~ 0.9.2 it was working fine. 

Going to try 1.0 to see if it happens there too. 

Edit: problem occurs on 1.0.0 too, rolled back to 0.9.2 and the problem went away as expected.

**Comment by masagrator** [comment]
Read Release Notes of 1.0.0 version.
