### ISSUE TITLE
Status Monitor keeps closing

### ISSUE THREAD

**Issue by VorgonBattlecruiser** [masagrator/Status-Monitor-Overlay#70]
Whenever i try to enable status monitor ingame to monitor clocks and/or framerate it shows for a moment and then very quickly returns to the previous menu where you can chose between mini, micro, fps only etc.

its repeatable and happens no matter which of those options i chose or which game i try and use them with

**Comment by VorgonBattlecruiser** [comment]
switch oled, fw17, atmosphere 1.6.2, hekate 6.0.7
running plugins such as edizon, quickntp, missioncontrol, switch oc suite.
tesla and all related plugins all always at their latest version.
1tb microsd with about 3gb of space left.
dont really know what else to say tbh

**Comment by muxi1** [comment]
Another user has reported this problem. Apparently it does not seem to exist under version 0.9 2. This may help with troubleshooting.

**Comment by VorgonBattlecruiser** [comment]
i actually know why now.
this only happens when you set the tesla overlay hotkey combo to RSTICK+LSTICK
either changing that combo OR using the config.ini template in the config folder to set up a different hotkey combo for status monitor will fix it.
Wow, ive been playing around with SO many possible reasons as to why this could be and it turned out to be something so simple and silly.

**Comment by VorgonBattlecruiser** [comment]
God, i cant believe status monitor finally works again.
Im so happy right now, not even joking.
I really missed overclocking, underclocking etc etc and without status monitor theres just no point to any of that.

LOVE your work and really appreciate it!
... is it weird that im kinda proud of myself for finally figuring out why it kept closing? ^^;;;

**Comment by masagrator** [comment]
Yes, you are a rare kind of person that tries to figure out where issue is instead of waiting for solution, which I approve. I couldn't reproduce this issue because I didn't know what was causing it. With this I can start somewhere. Dunno why this happened though, because when testing 1.0.0 build this combo worked fine, but I stopped using that combo and something must have happened after that.

**Comment by VorgonBattlecruiser** [comment]
im just happy that i finally got my status monitor back, thanks again for everything!

**Comment by masagrator** [comment]
Since it's been a month and no response, I guess it's fixed.
