### ISSUE TITLE
Idea question: Share Status Data over MQTT

### ISSUE THREAD

**Issue by monte-burns** [masagrator/Status-Monitor-Overlay#75]
Hi, 

I am a big fan of your work! I was wondering if it would be possible to integrate and export the data over MQTT to be used with Home Assistant for example.

The use case here being to know and visualise when games are being played to trigger certain automations.

As an idea, would this be technically possible?

**Comment by masagrator** [comment]
Hi.

I won't add it because of memory constraints. Adding network functions would mean additional free space required to run overlay, and already as it is Status Monitor is pretty ram hungry.

**Comment by monte-burns** [comment]
Ah clear makes sense! Thanks for the explanation!!
