### ISSUE TITLE
FPS Locked to 254

### ISSUE THREAD

**Issue by Dr01000111** [masagrator/Status-Monitor-Overlay#78]
as of the latest update of salty nx and Status moniter over lay on atomsphere 1.7.1 switch firmware 18.1.0 the fps counter is locked to 254.0

**Comment by masagrator** [comment]
Either you didn't update stuff properly (then I recommend to read READMEs and release notes) or you are testing it on game that is not compatible with SaltyNX (again read readme of SaltyNX).
