### ISSUE TITLE
(Feature request) Change the position of the mini window

### ISSUE THREAD

**Issue by Conan179** [masagrator/Status-Monitor-Overlay#8]
Would it be possible to incorporate an option with which you can determine where on the display the mini window is located? e.g. stats top left, top right.

**Comment by masagrator** [comment]
It could be done for top left and bottom left, doing right side will require additional work as it will be outside of specified framebuffer.

Maybe some day.

**Comment by masagrator** [comment]
After so much time I can say I won't do it. Use Micro mode if you want something more minimalistic than mini mode.
