### ISSUE TITLE
Status-Monitor + sys-clk freeze

### ISSUE THREAD

**Issue by jecoteco** [masagrator/Status-Monitor-Overlay#80]
I'm trying to get an FPS compare. Unfortunately trying to get FPS to show via status overlay and running either sys-ck or 4ifir (basically any overclock override) ends of freezing the console.

tested using Atmosphere 1.6.4 + 1.7.1, on firmware 17.0.1 + 18.1.0 on oled console. Tested on 4IFIR 2.3 on firmware 17.0.1 +  18.0.0 + 18.1.0
the same problem persists on multiple atmosphere and firmware versions.

**Comment by masagrator** [comment]
Only one person had this issue recently and it turned out that their voltages were bad. Remove loader.kip from atmosphere/kips and try again

**Comment by jecoteco** [comment]
The version of sys-clk I'm using is not using loader.kip, nor is it used in the hekate boot process. Although I do have several oled switches each with a different firmware. I conclude that the problem persists with or without kips. if you have had an issue related to voltages what are the chances that all 3 oleds have this issue?

**Comment by masagrator** [comment]
I won't be helping with solving pack issues. Install clean atmosphere, then sys-clk and come back.

This pack has many sysmodules and patches ingering in sysmodules.

**Comment by masagrator** [comment]
And of course you have newest SaltyNX and Status Monitor?

**Comment by jecoteco** [comment]
True that this pack was heavily modified but the modules were all original with the exception of sys-clk. I configured it to use my own github page to redirect uberhand to update from official sources. So SaltyNX is original. I will test with original sys-clk, but I expect same result.
